server:
  port: 8085

spring:
  application:
    name: catalog-service

  datasource:
    url: jdbc:mysql://localhost:3306/catalog?createDatabaseIfNotExist=true
    username: root
    password: Abhi@11399
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
