server:
  port: 8090

spring:
  application:
    name: notification-service

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    listener:
      simple:
        retry:
          enabled: true
          max-attempts: 3
          initial-interval: 2000
          multiplier: 2
          max-interval: 10000
        default-requeue-rejected: false

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
